-- phpMyAdmin SQL Dump
-- version 3.4.10.1deb1
-- http://www.phpmyadmin.net
--
-- Host: localhost
-- Generation Time: Oct 01, 2014 at 01:29 AM
-- Server version: 5.5.37
-- PHP Version: 5.3.10-1ubuntu3.12

SET SQL_MODE="NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- Database: `smartAd_3G`
--

-- --------------------------------------------------------

--
-- Table structure for table `wp_commentmeta`
--

DROP TABLE IF EXISTS `wp_commentmeta`;
CREATE TABLE IF NOT EXISTS `wp_commentmeta` (
  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `comment_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` longtext,
  PRIMARY KEY (`meta_id`),
  KEY `comment_id` (`comment_id`),
  KEY `meta_key` (`meta_key`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `wp_comments`
--

DROP TABLE IF EXISTS `wp_comments`;
CREATE TABLE IF NOT EXISTS `wp_comments` (
  `comment_ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `comment_post_ID` bigint(20) unsigned NOT NULL DEFAULT '0',
  `comment_author` tinytext NOT NULL,
  `comment_author_email` varchar(100) NOT NULL DEFAULT '',
  `comment_author_url` varchar(200) NOT NULL DEFAULT '',
  `comment_author_IP` varchar(100) NOT NULL DEFAULT '',
  `comment_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `comment_content` text NOT NULL,
  `comment_karma` int(11) NOT NULL DEFAULT '0',
  `comment_approved` varchar(20) NOT NULL DEFAULT '1',
  `comment_agent` varchar(255) NOT NULL DEFAULT '',
  `comment_type` varchar(20) NOT NULL DEFAULT '',
  `comment_parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  PRIMARY KEY (`comment_ID`),
  KEY `comment_post_ID` (`comment_post_ID`),
  KEY `comment_approved_date_gmt` (`comment_approved`,`comment_date_gmt`),
  KEY `comment_date_gmt` (`comment_date_gmt`),
  KEY `comment_parent` (`comment_parent`),
  KEY `comment_author_email` (`comment_author_email`(10))
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

--
-- Dumping data for table `wp_comments`
--

INSERT INTO `wp_comments` (`comment_ID`, `comment_post_ID`, `comment_author`, `comment_author_email`, `comment_author_url`, `comment_author_IP`, `comment_date`, `comment_date_gmt`, `comment_content`, `comment_karma`, `comment_approved`, `comment_agent`, `comment_type`, `comment_parent`, `user_id`) VALUES
(1, 1, 'Mr WordPress', '', 'https://wordpress.org/', '', '2014-09-29 16:51:28', '2014-09-29 16:51:28', 'Hi, this is a comment.\nTo delete a comment, just log in and view the post&#039;s comments. There you will have the option to edit or delete them.', 0, '1', '', '', 0, 0);

-- --------------------------------------------------------

--
-- Table structure for table `wp_huge_itslider_images`
--

DROP TABLE IF EXISTS `wp_huge_itslider_images`;
CREATE TABLE IF NOT EXISTS `wp_huge_itslider_images` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(100) DEFAULT NULL,
  `slider_id` varchar(200) DEFAULT NULL,
  `description` text,
  `image_url` text,
  `sl_url` varchar(128) DEFAULT NULL,
  `sl_type` text NOT NULL,
  `link_target` text NOT NULL,
  `sl_stitle` text NOT NULL,
  `sl_sdesc` text NOT NULL,
  `sl_postlink` text NOT NULL,
  `ordering` int(11) NOT NULL,
  `published` tinyint(4) unsigned DEFAULT NULL,
  `published_in_sl_width` tinyint(4) unsigned DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=5 ;

--
-- Dumping data for table `wp_huge_itslider_images`
--

INSERT INTO `wp_huge_itslider_images` (`id`, `name`, `slider_id`, `description`, `image_url`, `sl_url`, `sl_type`, `link_target`, `sl_stitle`, `sl_sdesc`, `sl_postlink`, `ordering`, `published`, `published_in_sl_width`) VALUES
(1, '', '1', '', 'http://localhost/wordpress/wp-content/plugins/slider-image/Front_images/slides/slide1.jpg', 'http://huge-it.com', 'image', 'on', '', '', '', 1, 1, NULL),
(2, 'Simple Usage', '1', '', 'http://localhost/wordpress/wp-content/plugins/slider-image/Front_images/slides/slide2.jpg', 'http://huge-it.com', 'image', 'on', '', '', '', 2, 1, NULL),
(3, 'Huge-IT Slider', '1', 'The slider allows having unlimited amount of images with their titles and descriptions. The slider uses autogenerated shortcodes making it easier for the users to add it to the custom location.', 'http://localhost/wordpress/wp-content/plugins/slider-image/Front_images/slides/slide3.jpg', 'http://huge-it.com', 'image', 'on', '', '', '', 3, 1, NULL);

-- --------------------------------------------------------

--
-- Table structure for table `wp_huge_itslider_params`
--

DROP TABLE IF EXISTS `wp_huge_itslider_params`;
CREATE TABLE IF NOT EXISTS `wp_huge_itslider_params` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(50) CHARACTER SET utf8 NOT NULL,
  `title` varchar(200) CHARACTER SET utf8 NOT NULL,
  `description` text CHARACTER SET utf8 NOT NULL,
  `value` varchar(200) CHARACTER SET utf8 NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=latin1 AUTO_INCREMENT=126 ;

--
-- Dumping data for table `wp_huge_itslider_params`
--

INSERT INTO `wp_huge_itslider_params` (`id`, `name`, `title`, `description`, `value`) VALUES
(89, 'slider_crop_image', 'Slider crop image', 'Slider crop image', 'resize'),
(90, 'slider_title_color', 'Slider title color', 'Slider title color', '000000'),
(91, 'slider_title_font_size', 'Slider title font size', 'Slider title font size', '13'),
(92, 'slider_description_color', 'Slider description color', 'Slider description color', 'ffffff'),
(93, 'slider_description_font_size', 'Slider description font size', 'Slider description font size', '13'),
(94, 'slider_title_position', 'Slider title position', 'Slider title position', 'right-top'),
(95, 'slider_description_position', 'Slider description position', 'Slider description position', 'right-bottom'),
(96, 'slider_title_border_size', 'Slider Title border size', 'Slider Title border size', '0'),
(97, 'slider_title_border_color', 'Slider title border color', 'Slider title border color', 'ffffff'),
(98, 'slider_title_border_radius', 'Slider title border radius', 'Slider title border radius', '4'),
(99, 'slider_description_border_size', 'Slider description border size', 'Slider description border size', '0'),
(100, 'slider_description_border_color', 'Slider description border color', 'Slider description border color', 'ffffff'),
(101, 'slider_description_border_radius', 'Slider description border radius', 'Slider description border radius', '0'),
(102, 'slider_slideshow_border_size', 'Slider border size', 'Slider border size', '0'),
(103, 'slider_slideshow_border_color', 'Slider border color', 'Slider border color', 'ffffff'),
(104, 'slider_slideshow_border_radius', 'Slider border radius', 'Slider border radius', '0'),
(105, 'slider_navigation_type', 'Slider navigation type', 'Slider navigation type', '1'),
(106, 'slider_navigation_position', 'Slider navigation position', 'Slider navigation position', 'bottom'),
(107, 'slider_title_background_color', 'Slider title background color', 'Slider title background color', 'ffffff'),
(108, 'slider_description_background_color', 'Slider description background color', 'Slider description background color', '000000'),
(109, 'slider_title_transparent', 'Slider title has background', 'Slider title has background', 'on'),
(110, 'slider_description_transparent', 'Slider description has background', 'Slider description has background', 'on'),
(111, 'slider_slider_background_color', 'Slider slider background color', 'Slider slider background color', 'ffffff'),
(112, 'slider_dots_position', 'slider dots position', 'slider dots position', 'top'),
(113, 'slider_active_dot_color', 'slider active dot color', '', 'ffffff'),
(114, 'slider_dots_color', 'slider dots color', '', '000000'),
(115, 'slider_description_width', 'Slider description width', 'Slider description width', '70'),
(116, 'slider_description_height', 'Slider description height', 'Slider description height', '50'),
(117, 'slider_description_background_transparency', 'slider description background transparency', 'slider description background transparency', '70'),
(118, 'slider_description_text_align', 'description text-align', 'description text-align', 'justify'),
(119, 'slider_title_width', 'slider title width', 'slider title width', '30'),
(120, 'slider_title_height', 'slider title height', 'slider title height', '50'),
(121, 'slider_title_background_transparency', 'slider title background transparency', 'slider title background transparency', '70'),
(122, 'slider_title_text_align', 'title text-align', 'title text-align', 'right'),
(123, 'slider_title_has_margin', 'title has margin', 'title has margin', 'on'),
(124, 'slider_description_has_margin', 'description has margin', 'description has margin', 'on'),
(125, 'slider_show_arrows', 'Slider show left right arrows', 'Slider show left right arrows', 'on');

-- --------------------------------------------------------

--
-- Table structure for table `wp_huge_itslider_sliders`
--

DROP TABLE IF EXISTS `wp_huge_itslider_sliders`;
CREATE TABLE IF NOT EXISTS `wp_huge_itslider_sliders` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL,
  `sl_height` int(11) unsigned DEFAULT NULL,
  `sl_width` int(11) unsigned DEFAULT NULL,
  `pause_on_hover` text,
  `slider_list_effects_s` text,
  `description` text,
  `param` text,
  `sl_position` text NOT NULL,
  `ordering` int(11) NOT NULL,
  `published` text,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id` (`id`)
) ENGINE=MyISAM  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

--
-- Dumping data for table `wp_huge_itslider_sliders`
--

INSERT INTO `wp_huge_itslider_sliders` (`id`, `name`, `sl_height`, `sl_width`, `pause_on_hover`, `slider_list_effects_s`, `description`, `param`, `sl_position`, `ordering`, `published`) VALUES
(1, 'My First Slider', 376, 760, 'on', 'random', '4000', '1000', 'center', 1, '300');

-- --------------------------------------------------------

--
-- Table structure for table `wp_links`
--

DROP TABLE IF EXISTS `wp_links`;
CREATE TABLE IF NOT EXISTS `wp_links` (
  `link_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `link_url` varchar(255) NOT NULL DEFAULT '',
  `link_name` varchar(255) NOT NULL DEFAULT '',
  `link_image` varchar(255) NOT NULL DEFAULT '',
  `link_target` varchar(25) NOT NULL DEFAULT '',
  `link_description` varchar(255) NOT NULL DEFAULT '',
  `link_visible` varchar(20) NOT NULL DEFAULT 'Y',
  `link_owner` bigint(20) unsigned NOT NULL DEFAULT '1',
  `link_rating` int(11) NOT NULL DEFAULT '0',
  `link_updated` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `link_rel` varchar(255) NOT NULL DEFAULT '',
  `link_notes` mediumtext NOT NULL,
  `link_rss` varchar(255) NOT NULL DEFAULT '',
  PRIMARY KEY (`link_id`),
  KEY `link_visible` (`link_visible`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 AUTO_INCREMENT=1 ;

-- --------------------------------------------------------

--
-- Table structure for table `wp_options`
--

DROP TABLE IF EXISTS `wp_options`;
CREATE TABLE IF NOT EXISTS `wp_options` (
  `option_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `option_name` varchar(64) NOT NULL DEFAULT '',
  `option_value` longtext NOT NULL,
  `autoload` varchar(20) NOT NULL DEFAULT 'yes',
  PRIMARY KEY (`option_id`),
  UNIQUE KEY `option_name` (`option_name`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=165 ;

--
-- Dumping data for table `wp_options`
--

INSERT INTO `wp_options` (`option_id`, `option_name`, `option_value`, `autoload`) VALUES
(1, 'siteurl', 'http://localhost/wordpress', 'yes'),
(2, 'home', 'http://localhost/wordpress', 'yes'),
(3, 'blogname', 'Dịch Vụ Đăng Ký 3G Mobifone', 'yes'),
(4, 'blogdescription', 'Just another WordPress site', 'yes'),
(5, 'users_can_register', '0', 'yes'),
(6, 'admin_email', 'daobv@gmail.com', 'yes'),
(7, 'start_of_week', '1', 'yes'),
(8, 'use_balanceTags', '0', 'yes'),
(9, 'use_smilies', '1', 'yes'),
(10, 'require_name_email', '1', 'yes'),
(11, 'comments_notify', '1', 'yes'),
(12, 'posts_per_rss', '10', 'yes'),
(13, 'rss_use_excerpt', '0', 'yes'),
(14, 'mailserver_url', 'mail.example.com', 'yes'),
(15, 'mailserver_login', 'login@example.com', 'yes'),
(16, 'mailserver_pass', 'password', 'yes'),
(17, 'mailserver_port', '110', 'yes'),
(18, 'default_category', '1', 'yes'),
(19, 'default_comment_status', 'open', 'yes'),
(20, 'default_ping_status', 'open', 'yes'),
(21, 'default_pingback_flag', '1', 'yes'),
(22, 'posts_per_page', '10', 'yes'),
(23, 'date_format', 'F j, Y', 'yes'),
(24, 'time_format', 'g:i a', 'yes'),
(25, 'links_updated_date_format', 'F j, Y g:i a', 'yes'),
(26, 'comment_moderation', '0', 'yes'),
(27, 'moderation_notify', '1', 'yes'),
(28, 'permalink_structure', '/index.php/%postname%/', 'yes'),
(29, 'gzipcompression', '0', 'yes'),
(30, 'hack_file', '0', 'yes'),
(31, 'blog_charset', 'UTF-8', 'yes'),
(32, 'moderation_keys', '', 'no'),
(33, 'active_plugins', 'a:1:{i:0;s:23:"slider-image/slider.php";}', 'yes'),
(34, 'category_base', '', 'yes'),
(35, 'ping_sites', 'http://rpc.pingomatic.com/', 'yes'),
(36, 'advanced_edit', '0', 'yes'),
(37, 'comment_max_links', '2', 'yes'),
(38, 'gmt_offset', '0', 'yes'),
(39, 'default_email_category', '1', 'yes'),
(40, 'recently_edited', 'a:2:{i:0;s:55:"/var/www/wordpress/wp-content/themes/imag-mag/style.css";i:1;s:0:"";}', 'no'),
(41, 'template', 'imag-mag', 'yes'),
(42, 'stylesheet', 'imag-mag', 'yes'),
(43, 'comment_whitelist', '1', 'yes'),
(44, 'blacklist_keys', '', 'no'),
(45, 'comment_registration', '0', 'yes'),
(46, 'html_type', 'text/html', 'yes'),
(47, 'use_trackback', '0', 'yes'),
(48, 'default_role', 'subscriber', 'yes'),
(49, 'db_version', '29630', 'yes'),
(50, 'uploads_use_yearmonth_folders', '1', 'yes'),
(51, 'upload_path', '', 'yes'),
(52, 'blog_public', '1', 'yes'),
(53, 'default_link_category', '2', 'yes'),
(54, 'show_on_front', 'posts', 'yes'),
(55, 'tag_base', '', 'yes'),
(56, 'show_avatars', '1', 'yes'),
(57, 'avatar_rating', 'G', 'yes'),
(58, 'upload_url_path', '', 'yes'),
(59, 'thumbnail_size_w', '150', 'yes'),
(60, 'thumbnail_size_h', '150', 'yes'),
(61, 'thumbnail_crop', '1', 'yes'),
(62, 'medium_size_w', '300', 'yes'),
(63, 'medium_size_h', '300', 'yes'),
(64, 'avatar_default', 'mystery', 'yes'),
(65, 'large_size_w', '1024', 'yes'),
(66, 'large_size_h', '1024', 'yes'),
(67, 'image_default_link_type', 'file', 'yes'),
(68, 'image_default_size', '', 'yes'),
(69, 'image_default_align', '', 'yes'),
(70, 'close_comments_for_old_posts', '0', 'yes'),
(71, 'close_comments_days_old', '14', 'yes'),
(72, 'thread_comments', '1', 'yes'),
(73, 'thread_comments_depth', '5', 'yes'),
(74, 'page_comments', '0', 'yes'),
(75, 'comments_per_page', '50', 'yes'),
(76, 'default_comments_page', 'newest', 'yes'),
(77, 'comment_order', 'asc', 'yes'),
(78, 'sticky_posts', 'a:0:{}', 'yes'),
(79, 'widget_categories', 'a:2:{i:2;a:4:{s:5:"title";s:0:"";s:5:"count";i:0;s:12:"hierarchical";i:0;s:8:"dropdown";i:0;}s:12:"_multiwidget";i:1;}', 'yes'),
(80, 'widget_text', 'a:1:{s:12:"_multiwidget";i:1;}', 'yes'),
(81, 'widget_rss', 'a:0:{}', 'yes'),
(82, 'uninstall_plugins', 'a:0:{}', 'no'),
(83, 'timezone_string', '', 'yes'),
(84, 'page_for_posts', '0', 'yes'),
(85, 'page_on_front', '0', 'yes'),
(86, 'default_post_format', '0', 'yes'),
(87, 'link_manager_enabled', '0', 'yes'),
(88, 'initial_db_version', '29630', 'yes'),
(89, 'wp_user_roles', 'a:5:{s:13:"administrator";a:2:{s:4:"name";s:13:"Administrator";s:12:"capabilities";a:62:{s:13:"switch_themes";b:1;s:11:"edit_themes";b:1;s:16:"activate_plugins";b:1;s:12:"edit_plugins";b:1;s:10:"edit_users";b:1;s:10:"edit_files";b:1;s:14:"manage_options";b:1;s:17:"moderate_comments";b:1;s:17:"manage_categories";b:1;s:12:"manage_links";b:1;s:12:"upload_files";b:1;s:6:"import";b:1;s:15:"unfiltered_html";b:1;s:10:"edit_posts";b:1;s:17:"edit_others_posts";b:1;s:20:"edit_published_posts";b:1;s:13:"publish_posts";b:1;s:10:"edit_pages";b:1;s:4:"read";b:1;s:8:"level_10";b:1;s:7:"level_9";b:1;s:7:"level_8";b:1;s:7:"level_7";b:1;s:7:"level_6";b:1;s:7:"level_5";b:1;s:7:"level_4";b:1;s:7:"level_3";b:1;s:7:"level_2";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:17:"edit_others_pages";b:1;s:20:"edit_published_pages";b:1;s:13:"publish_pages";b:1;s:12:"delete_pages";b:1;s:19:"delete_others_pages";b:1;s:22:"delete_published_pages";b:1;s:12:"delete_posts";b:1;s:19:"delete_others_posts";b:1;s:22:"delete_published_posts";b:1;s:20:"delete_private_posts";b:1;s:18:"edit_private_posts";b:1;s:18:"read_private_posts";b:1;s:20:"delete_private_pages";b:1;s:18:"edit_private_pages";b:1;s:18:"read_private_pages";b:1;s:12:"delete_users";b:1;s:12:"create_users";b:1;s:17:"unfiltered_upload";b:1;s:14:"edit_dashboard";b:1;s:14:"update_plugins";b:1;s:14:"delete_plugins";b:1;s:15:"install_plugins";b:1;s:13:"update_themes";b:1;s:14:"install_themes";b:1;s:11:"update_core";b:1;s:10:"list_users";b:1;s:12:"remove_users";b:1;s:9:"add_users";b:1;s:13:"promote_users";b:1;s:18:"edit_theme_options";b:1;s:13:"delete_themes";b:1;s:6:"export";b:1;}}s:6:"editor";a:2:{s:4:"name";s:6:"Editor";s:12:"capabilities";a:34:{s:17:"moderate_comments";b:1;s:17:"manage_categories";b:1;s:12:"manage_links";b:1;s:12:"upload_files";b:1;s:15:"unfiltered_html";b:1;s:10:"edit_posts";b:1;s:17:"edit_others_posts";b:1;s:20:"edit_published_posts";b:1;s:13:"publish_posts";b:1;s:10:"edit_pages";b:1;s:4:"read";b:1;s:7:"level_7";b:1;s:7:"level_6";b:1;s:7:"level_5";b:1;s:7:"level_4";b:1;s:7:"level_3";b:1;s:7:"level_2";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:17:"edit_others_pages";b:1;s:20:"edit_published_pages";b:1;s:13:"publish_pages";b:1;s:12:"delete_pages";b:1;s:19:"delete_others_pages";b:1;s:22:"delete_published_pages";b:1;s:12:"delete_posts";b:1;s:19:"delete_others_posts";b:1;s:22:"delete_published_posts";b:1;s:20:"delete_private_posts";b:1;s:18:"edit_private_posts";b:1;s:18:"read_private_posts";b:1;s:20:"delete_private_pages";b:1;s:18:"edit_private_pages";b:1;s:18:"read_private_pages";b:1;}}s:6:"author";a:2:{s:4:"name";s:6:"Author";s:12:"capabilities";a:10:{s:12:"upload_files";b:1;s:10:"edit_posts";b:1;s:20:"edit_published_posts";b:1;s:13:"publish_posts";b:1;s:4:"read";b:1;s:7:"level_2";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:12:"delete_posts";b:1;s:22:"delete_published_posts";b:1;}}s:11:"contributor";a:2:{s:4:"name";s:11:"Contributor";s:12:"capabilities";a:5:{s:10:"edit_posts";b:1;s:4:"read";b:1;s:7:"level_1";b:1;s:7:"level_0";b:1;s:12:"delete_posts";b:1;}}s:10:"subscriber";a:2:{s:4:"name";s:10:"Subscriber";s:12:"capabilities";a:2:{s:4:"read";b:1;s:7:"level_0";b:1;}}}', 'yes'),
(90, 'widget_search', 'a:1:{s:12:"_multiwidget";i:1;}', 'yes'),
(91, 'widget_recent-posts', 'a:2:{i:2;a:2:{s:5:"title";s:0:"";s:6:"number";i:5;}s:12:"_multiwidget";i:1;}', 'yes'),
(92, 'widget_recent-comments', 'a:2:{i:2;a:2:{s:5:"title";s:0:"";s:6:"number";i:5;}s:12:"_multiwidget";i:1;}', 'yes'),
(93, 'widget_archives', 'a:1:{s:12:"_multiwidget";i:1;}', 'yes'),
(94, 'widget_meta', 'a:1:{s:12:"_multiwidget";i:1;}', 'yes'),
(95, 'sidebars_widgets', 'a:8:{s:19:"wp_inactive_widgets";a:0:{}s:9:"sidebar-1";a:4:{i:0;s:7:"pages-2";i:1;s:14:"recent-posts-2";i:2;s:17:"recent-comments-2";i:3;s:12:"categories-2";}s:9:"sidebar-2";a:0:{}s:9:"sidebar-3";a:0:{}s:9:"sidebar-4";a:0:{}s:9:"sidebar-5";a:0:{}s:9:"sidebar-6";a:0:{}s:13:"array_version";i:3;}', 'yes'),
(96, 'cron', 'a:5:{i:1412105940;a:1:{s:20:"wp_maybe_auto_update";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1412139097;a:3:{s:16:"wp_version_check";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:17:"wp_update_plugins";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}s:16:"wp_update_themes";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:10:"twicedaily";s:4:"args";a:0:{}s:8:"interval";i:43200;}}}i:1412182335;a:1:{s:19:"wp_scheduled_delete";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}i:1412182808;a:1:{s:30:"wp_scheduled_auto_draft_delete";a:1:{s:32:"40cd750bba9870f18aada2478b24840a";a:3:{s:8:"schedule";s:5:"daily";s:4:"args";a:0:{}s:8:"interval";i:86400;}}}s:7:"version";i:2;}', 'yes'),
(98, '_site_transient_update_core', 'O:8:"stdClass":4:{s:7:"updates";a:1:{i:0;O:8:"stdClass":10:{s:8:"response";s:6:"latest";s:8:"download";s:57:"https://downloads.wordpress.org/release/wordpress-4.0.zip";s:6:"locale";s:5:"en_US";s:8:"packages";O:8:"stdClass":5:{s:4:"full";s:57:"https://downloads.wordpress.org/release/wordpress-4.0.zip";s:10:"no_content";s:68:"https://downloads.wordpress.org/release/wordpress-4.0-no-content.zip";s:11:"new_bundled";s:69:"https://downloads.wordpress.org/release/wordpress-4.0-new-bundled.zip";s:7:"partial";b:0;s:8:"rollback";b:0;}s:7:"current";s:3:"4.0";s:7:"version";s:3:"4.0";s:11:"php_version";s:5:"5.2.4";s:13:"mysql_version";s:3:"5.0";s:11:"new_bundled";s:3:"3.8";s:15:"partial_version";s:0:"";}}s:12:"last_checked";i:1412095913;s:15:"version_checked";s:3:"4.0";s:12:"translations";a:0:{}}', 'yes'),
(99, '_transient_random_seed', '7f601ff0bffa3fcf9affc86afdce836e', 'yes'),
(100, '_site_transient_update_plugins', 'O:8:"stdClass":4:{s:12:"last_checked";i:1412095920;s:8:"response";a:0:{}s:12:"translations";a:0:{}s:9:"no_update";a:3:{s:19:"akismet/akismet.php";O:8:"stdClass":6:{s:2:"id";s:2:"15";s:4:"slug";s:7:"akismet";s:6:"plugin";s:19:"akismet/akismet.php";s:11:"new_version";s:5:"3.0.2";s:3:"url";s:38:"https://wordpress.org/plugins/akismet/";s:7:"package";s:56:"https://downloads.wordpress.org/plugin/akismet.3.0.2.zip";}s:9:"hello.php";O:8:"stdClass":6:{s:2:"id";s:4:"3564";s:4:"slug";s:11:"hello-dolly";s:6:"plugin";s:9:"hello.php";s:11:"new_version";s:3:"1.6";s:3:"url";s:42:"https://wordpress.org/plugins/hello-dolly/";s:7:"package";s:58:"https://downloads.wordpress.org/plugin/hello-dolly.1.6.zip";}s:23:"slider-image/slider.php";O:8:"stdClass":6:{s:2:"id";s:5:"49075";s:4:"slug";s:12:"slider-image";s:6:"plugin";s:23:"slider-image/slider.php";s:11:"new_version";s:5:"2.6.3";s:3:"url";s:43:"https://wordpress.org/plugins/slider-image/";s:7:"package";s:61:"https://downloads.wordpress.org/plugin/slider-image.2.6.3.zip";}}}', 'yes'),
(104, '_site_transient_update_themes', 'O:8:"stdClass":4:{s:12:"last_checked";i:1412095925;s:7:"checked";a:4:{s:8:"imag-mag";s:5:"1.0.3";s:14:"twentyfourteen";s:3:"1.2";s:14:"twentythirteen";s:3:"1.3";s:12:"twentytwelve";s:3:"1.5";}s:8:"response";a:0:{}s:12:"translations";a:0:{}}', 'yes'),
(105, '_site_transient_timeout_browser_9144b8475a7ea4baab9c7fb910a15a58', '1412614312', 'yes'),
(106, '_site_transient_browser_9144b8475a7ea4baab9c7fb910a15a58', 'a:9:{s:8:"platform";s:5:"Linux";s:4:"name";s:6:"Chrome";s:7:"version";s:13:"35.0.1916.153";s:10:"update_url";s:28:"http://www.google.com/chrome";s:7:"img_src";s:49:"http://s.wordpress.org/images/browsers/chrome.png";s:11:"img_src_ssl";s:48:"https://wordpress.org/images/browsers/chrome.png";s:15:"current_version";s:2:"18";s:7:"upgrade";b:0;s:8:"insecure";b:0;}', 'yes'),
(107, 'can_compress_scripts', '0', 'yes'),
(114, '_transient_twentyfourteen_category_count', '1', 'yes'),
(123, '_transient_timeout_plugin_slugs', '1412097209', 'no'),
(124, '_transient_plugin_slugs', 'a:3:{i:0;s:19:"akismet/akismet.php";i:1;s:9:"hello.php";i:2;s:23:"slider-image/slider.php";}', 'no'),
(128, 'theme_mods_twentyfourteen', 'a:1:{s:16:"sidebars_widgets";a:2:{s:4:"time";i:1412009555;s:4:"data";a:4:{s:19:"wp_inactive_widgets";a:0:{}s:9:"sidebar-1";a:6:{i:0;s:8:"search-2";i:1;s:14:"recent-posts-2";i:2;s:17:"recent-comments-2";i:3;s:10:"archives-2";i:4;s:12:"categories-2";i:5;s:6:"meta-2";}s:9:"sidebar-2";a:0:{}s:9:"sidebar-3";a:0:{}}}}', 'yes'),
(129, 'current_theme', 'iMag Mag', 'yes'),
(130, 'theme_mods_twentytwelve', 'a:2:{i:0;b:0;s:16:"sidebars_widgets";a:2:{s:4:"time";i:1412011230;s:4:"data";a:4:{s:19:"wp_inactive_widgets";a:0:{}s:9:"sidebar-1";a:6:{i:0;s:8:"search-2";i:1;s:14:"recent-posts-2";i:2;s:17:"recent-comments-2";i:3;s:10:"archives-2";i:4;s:12:"categories-2";i:5;s:6:"meta-2";}s:9:"sidebar-2";a:0:{}s:9:"sidebar-3";a:0:{}}}}', 'yes'),
(131, 'theme_switched', '', 'yes'),
(132, 'theme_mods_imag-mag', 'a:2:{i:0;b:0;s:18:"nav_menu_locations";a:1:{s:6:"topNav";i:8;}}', 'yes'),
(133, 'iMag Mag_options', 'a:11:{s:14:"custom_favicon";s:0:"";s:11:"custom_logo";s:65:"http://localhost/wordpress/wp-content/uploads/2014/09/logo311.png";s:22:"custom_logo_margin_top";s:3:"4px";s:17:"custom_feedburner";s:0:"";s:16:"google_analytics";s:0:"";s:15:"shw_footer_widg";s:3:"yes";s:18:"offline_feat_slide";s:1:"0";s:19:"feat_slide_category";s:1:"0";s:16:"posts_navigation";s:2:"On";s:11:"posts_bread";s:3:"Off";s:10:"posts_tags";s:2:"On";}', 'yes'),
(140, 'category_children', 'a:1:{i:4;a:1:{i:0;i:5;}}', 'yes'),
(141, 'recently_activated', 'a:0:{}', 'yes'),
(151, '_transient_timeout_dash_4077549d03da2e451c8b5f002294ff51', '1412119117', 'no'),
(152, '_transient_dash_4077549d03da2e451c8b5f002294ff51', '<div class="rss-widget"><p><strong>RSS Error</strong>: WP HTTP Error: Couldn''t resolve host ''wordpress.org''</p></div><div class="rss-widget"><p><strong>RSS Error</strong>: WP HTTP Error: Couldn''t resolve host ''planet.wordpress.org''</p></div><div class="rss-widget"><ul></ul></div>', 'no'),
(155, 'rewrite_rules', 'a:67:{s:57:"index.php/category/(.+?)/feed/(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:52:"index.php/category/(.+?)/(feed|rdf|rss|rss2|atom)/?$";s:52:"index.php?category_name=$matches[1]&feed=$matches[2]";s:45:"index.php/category/(.+?)/page/?([0-9]{1,})/?$";s:53:"index.php?category_name=$matches[1]&paged=$matches[2]";s:27:"index.php/category/(.+?)/?$";s:35:"index.php?category_name=$matches[1]";s:54:"index.php/tag/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?tag=$matches[1]&feed=$matches[2]";s:49:"index.php/tag/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?tag=$matches[1]&feed=$matches[2]";s:42:"index.php/tag/([^/]+)/page/?([0-9]{1,})/?$";s:43:"index.php?tag=$matches[1]&paged=$matches[2]";s:24:"index.php/tag/([^/]+)/?$";s:25:"index.php?tag=$matches[1]";s:55:"index.php/type/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?post_format=$matches[1]&feed=$matches[2]";s:50:"index.php/type/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?post_format=$matches[1]&feed=$matches[2]";s:43:"index.php/type/([^/]+)/page/?([0-9]{1,})/?$";s:51:"index.php?post_format=$matches[1]&paged=$matches[2]";s:25:"index.php/type/([^/]+)/?$";s:33:"index.php?post_format=$matches[1]";s:48:".*wp-(atom|rdf|rss|rss2|feed|commentsrss2)\\.php$";s:18:"index.php?feed=old";s:20:".*wp-app\\.php(/.*)?$";s:19:"index.php?error=403";s:18:".*wp-register.php$";s:23:"index.php?register=true";s:42:"index.php/feed/(feed|rdf|rss|rss2|atom)/?$";s:27:"index.php?&feed=$matches[1]";s:37:"index.php/(feed|rdf|rss|rss2|atom)/?$";s:27:"index.php?&feed=$matches[1]";s:30:"index.php/page/?([0-9]{1,})/?$";s:28:"index.php?&paged=$matches[1]";s:51:"index.php/comments/feed/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?&feed=$matches[1]&withcomments=1";s:46:"index.php/comments/(feed|rdf|rss|rss2|atom)/?$";s:42:"index.php?&feed=$matches[1]&withcomments=1";s:54:"index.php/search/(.+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:40:"index.php?s=$matches[1]&feed=$matches[2]";s:49:"index.php/search/(.+)/(feed|rdf|rss|rss2|atom)/?$";s:40:"index.php?s=$matches[1]&feed=$matches[2]";s:42:"index.php/search/(.+)/page/?([0-9]{1,})/?$";s:41:"index.php?s=$matches[1]&paged=$matches[2]";s:24:"index.php/search/(.+)/?$";s:23:"index.php?s=$matches[1]";s:57:"index.php/author/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?author_name=$matches[1]&feed=$matches[2]";s:52:"index.php/author/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:50:"index.php?author_name=$matches[1]&feed=$matches[2]";s:45:"index.php/author/([^/]+)/page/?([0-9]{1,})/?$";s:51:"index.php?author_name=$matches[1]&paged=$matches[2]";s:27:"index.php/author/([^/]+)/?$";s:33:"index.php?author_name=$matches[1]";s:79:"index.php/([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/feed/(feed|rdf|rss|rss2|atom)/?$";s:80:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&feed=$matches[4]";s:74:"index.php/([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/(feed|rdf|rss|rss2|atom)/?$";s:80:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&feed=$matches[4]";s:67:"index.php/([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/page/?([0-9]{1,})/?$";s:81:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]&paged=$matches[4]";s:49:"index.php/([0-9]{4})/([0-9]{1,2})/([0-9]{1,2})/?$";s:63:"index.php?year=$matches[1]&monthnum=$matches[2]&day=$matches[3]";s:66:"index.php/([0-9]{4})/([0-9]{1,2})/feed/(feed|rdf|rss|rss2|atom)/?$";s:64:"index.php?year=$matches[1]&monthnum=$matches[2]&feed=$matches[3]";s:61:"index.php/([0-9]{4})/([0-9]{1,2})/(feed|rdf|rss|rss2|atom)/?$";s:64:"index.php?year=$matches[1]&monthnum=$matches[2]&feed=$matches[3]";s:54:"index.php/([0-9]{4})/([0-9]{1,2})/page/?([0-9]{1,})/?$";s:65:"index.php?year=$matches[1]&monthnum=$matches[2]&paged=$matches[3]";s:36:"index.php/([0-9]{4})/([0-9]{1,2})/?$";s:47:"index.php?year=$matches[1]&monthnum=$matches[2]";s:53:"index.php/([0-9]{4})/feed/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?year=$matches[1]&feed=$matches[2]";s:48:"index.php/([0-9]{4})/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?year=$matches[1]&feed=$matches[2]";s:41:"index.php/([0-9]{4})/page/?([0-9]{1,})/?$";s:44:"index.php?year=$matches[1]&paged=$matches[2]";s:23:"index.php/([0-9]{4})/?$";s:26:"index.php?year=$matches[1]";s:37:"index.php/.?.+?/attachment/([^/]+)/?$";s:32:"index.php?attachment=$matches[1]";s:47:"index.php/.?.+?/attachment/([^/]+)/trackback/?$";s:37:"index.php?attachment=$matches[1]&tb=1";s:67:"index.php/.?.+?/attachment/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:62:"index.php/.?.+?/attachment/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:62:"index.php/.?.+?/attachment/([^/]+)/comment-page-([0-9]{1,})/?$";s:50:"index.php?attachment=$matches[1]&cpage=$matches[2]";s:30:"index.php/(.?.+?)/trackback/?$";s:35:"index.php?pagename=$matches[1]&tb=1";s:50:"index.php/(.?.+?)/feed/(feed|rdf|rss|rss2|atom)/?$";s:47:"index.php?pagename=$matches[1]&feed=$matches[2]";s:45:"index.php/(.?.+?)/(feed|rdf|rss|rss2|atom)/?$";s:47:"index.php?pagename=$matches[1]&feed=$matches[2]";s:38:"index.php/(.?.+?)/page/?([0-9]{1,})/?$";s:48:"index.php?pagename=$matches[1]&paged=$matches[2]";s:45:"index.php/(.?.+?)/comment-page-([0-9]{1,})/?$";s:48:"index.php?pagename=$matches[1]&cpage=$matches[2]";s:30:"index.php/(.?.+?)(/[0-9]+)?/?$";s:47:"index.php?pagename=$matches[1]&page=$matches[2]";s:37:"index.php/[^/]+/attachment/([^/]+)/?$";s:32:"index.php?attachment=$matches[1]";s:47:"index.php/[^/]+/attachment/([^/]+)/trackback/?$";s:37:"index.php?attachment=$matches[1]&tb=1";s:67:"index.php/[^/]+/attachment/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:62:"index.php/[^/]+/attachment/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:62:"index.php/[^/]+/attachment/([^/]+)/comment-page-([0-9]{1,})/?$";s:50:"index.php?attachment=$matches[1]&cpage=$matches[2]";s:30:"index.php/([^/]+)/trackback/?$";s:31:"index.php?name=$matches[1]&tb=1";s:50:"index.php/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?name=$matches[1]&feed=$matches[2]";s:45:"index.php/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:43:"index.php?name=$matches[1]&feed=$matches[2]";s:38:"index.php/([^/]+)/page/?([0-9]{1,})/?$";s:44:"index.php?name=$matches[1]&paged=$matches[2]";s:45:"index.php/([^/]+)/comment-page-([0-9]{1,})/?$";s:44:"index.php?name=$matches[1]&cpage=$matches[2]";s:30:"index.php/([^/]+)(/[0-9]+)?/?$";s:43:"index.php?name=$matches[1]&page=$matches[2]";s:26:"index.php/[^/]+/([^/]+)/?$";s:32:"index.php?attachment=$matches[1]";s:36:"index.php/[^/]+/([^/]+)/trackback/?$";s:37:"index.php?attachment=$matches[1]&tb=1";s:56:"index.php/[^/]+/([^/]+)/feed/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:51:"index.php/[^/]+/([^/]+)/(feed|rdf|rss|rss2|atom)/?$";s:49:"index.php?attachment=$matches[1]&feed=$matches[2]";s:51:"index.php/[^/]+/([^/]+)/comment-page-([0-9]{1,})/?$";s:50:"index.php?attachment=$matches[1]&cpage=$matches[2]";}', 'yes'),
(156, 'widget_nav_menu', 'a:0:{}', 'yes'),
(157, 'nav_menu_options', 'a:2:{i:0;b:0;s:8:"auto_add";a:0:{}}', 'yes'),
(158, '_site_transient_timeout_theme_roots', '1412097388', 'yes'),
(159, '_site_transient_theme_roots', 'a:4:{s:8:"imag-mag";s:7:"/themes";s:14:"twentyfourteen";s:7:"/themes";s:14:"twentythirteen";s:7:"/themes";s:12:"twentytwelve";s:7:"/themes";}', 'yes'),
(164, 'widget_pages', 'a:2:{i:2;a:3:{s:5:"title";s:11:"Dịch Vụ";s:6:"sortby";s:10:"menu_order";s:7:"exclude";s:0:"";}s:12:"_multiwidget";i:1;}', 'yes');

-- --------------------------------------------------------

--
-- Table structure for table `wp_postmeta`
--

DROP TABLE IF EXISTS `wp_postmeta`;
CREATE TABLE IF NOT EXISTS `wp_postmeta` (
  `meta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `post_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` longtext,
  PRIMARY KEY (`meta_id`),
  KEY `post_id` (`post_id`),
  KEY `meta_key` (`meta_key`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=122 ;

--
-- Dumping data for table `wp_postmeta`
--

INSERT INTO `wp_postmeta` (`meta_id`, `post_id`, `meta_key`, `meta_value`) VALUES
(1, 2, '_wp_page_template', 'default'),
(2, 8, '_wp_attached_file', '2014/09/logo31-e1412012673720.png'),
(3, 8, '_wp_attachment_metadata', 'a:5:{s:5:"width";i:180;s:6:"height";i:81;s:4:"file";s:33:"2014/09/logo31-e1412012673720.png";s:5:"sizes";a:2:{s:9:"thumbnail";a:4:{s:4:"file";s:17:"logo31-150x90.png";s:5:"width";i:150;s:6:"height";i:90;s:9:"mime-type";s:9:"image/png";}s:17:"sb-post-thumbnail";a:4:{s:4:"file";s:16:"logo31-70x70.png";s:5:"width";i:70;s:6:"height";i:70;s:9:"mime-type";s:9:"image/png";}}s:10:"image_meta";a:11:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:0:"";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";s:11:"orientation";i:0;}}'),
(4, 8, '_wp_attachment_backup_sizes', 'a:1:{s:9:"full-orig";a:3:{s:5:"width";i:200;s:6:"height";i:90;s:4:"file";s:10:"logo31.png";}}'),
(5, 9, '_wp_attached_file', '2014/09/logo311.png'),
(6, 9, '_wp_attachment_metadata', 'a:5:{s:5:"width";i:200;s:6:"height";i:90;s:4:"file";s:19:"2014/09/logo311.png";s:5:"sizes";a:2:{s:9:"thumbnail";a:4:{s:4:"file";s:18:"logo311-150x90.png";s:5:"width";i:150;s:6:"height";i:90;s:9:"mime-type";s:9:"image/png";}s:17:"sb-post-thumbnail";a:4:{s:4:"file";s:17:"logo311-70x70.png";s:5:"width";i:70;s:6:"height";i:70;s:9:"mime-type";s:9:"image/png";}}s:10:"image_meta";a:11:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:0:"";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";s:11:"orientation";i:0;}}'),
(7, 10, '_edit_last', '1'),
(8, 10, '_edit_lock', '1412101454:1'),
(36, 1, '_edit_lock', '1412076980:1'),
(46, 21, '_wp_attached_file', '2014/09/3854_RinTinTin.jpg'),
(47, 21, '_wp_attachment_metadata', 'a:5:{s:5:"width";i:164;s:6:"height";i:200;s:4:"file";s:26:"2014/09/3854_RinTinTin.jpg";s:5:"sizes";a:4:{s:9:"thumbnail";a:4:{s:4:"file";s:26:"3854_RinTinTin-150x150.jpg";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:10:"image/jpeg";}s:9:"mag-image";a:4:{s:4:"file";s:26:"3854_RinTinTin-164x160.jpg";s:5:"width";i:164;s:6:"height";i:160;s:9:"mime-type";s:10:"image/jpeg";}s:10:"blog-image";a:4:{s:4:"file";s:26:"3854_RinTinTin-164x180.jpg";s:5:"width";i:164;s:6:"height";i:180;s:9:"mime-type";s:10:"image/jpeg";}s:17:"sb-post-thumbnail";a:4:{s:4:"file";s:24:"3854_RinTinTin-70x70.jpg";s:5:"width";i:70;s:6:"height";i:70;s:9:"mime-type";s:10:"image/jpeg";}}s:10:"image_meta";a:11:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:0:"";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";s:11:"orientation";i:0;}}'),
(48, 20, '_edit_last', '1'),
(49, 20, '_edit_lock', '1412101139:1'),
(68, 26, '_menu_item_type', 'custom'),
(69, 26, '_menu_item_menu_item_parent', '0'),
(70, 26, '_menu_item_object_id', '26'),
(71, 26, '_menu_item_object', 'custom'),
(72, 26, '_menu_item_target', ''),
(73, 26, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(74, 26, '_menu_item_xfn', ''),
(75, 26, '_menu_item_url', 'http://localhost/wordpress/'),
(77, 27, '_menu_item_type', 'taxonomy'),
(78, 27, '_menu_item_menu_item_parent', '0'),
(79, 27, '_menu_item_object_id', '3'),
(80, 27, '_menu_item_object', 'category'),
(81, 27, '_menu_item_target', ''),
(82, 27, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(83, 27, '_menu_item_xfn', ''),
(84, 27, '_menu_item_url', ''),
(86, 28, '_menu_item_type', 'taxonomy'),
(87, 28, '_menu_item_menu_item_parent', '0'),
(88, 28, '_menu_item_object_id', '4'),
(89, 28, '_menu_item_object', 'category'),
(90, 28, '_menu_item_target', ''),
(91, 28, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(92, 28, '_menu_item_xfn', ''),
(93, 28, '_menu_item_url', ''),
(95, 29, '_menu_item_type', 'taxonomy'),
(96, 29, '_menu_item_menu_item_parent', '28'),
(97, 29, '_menu_item_object_id', '5'),
(98, 29, '_menu_item_object', 'category'),
(99, 29, '_menu_item_target', ''),
(100, 29, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(101, 29, '_menu_item_xfn', ''),
(102, 29, '_menu_item_url', ''),
(104, 30, '_menu_item_type', 'post_type'),
(105, 30, '_menu_item_menu_item_parent', '28'),
(106, 30, '_menu_item_object_id', '20'),
(107, 30, '_menu_item_object', 'page'),
(108, 30, '_menu_item_target', ''),
(109, 30, '_menu_item_classes', 'a:1:{i:0;s:0:"";}'),
(110, 30, '_menu_item_xfn', ''),
(111, 30, '_menu_item_url', ''),
(113, 20, '_thumbnail_id', '21'),
(114, 2, '_edit_lock', '1412097722:1'),
(115, 32, '_wp_attached_file', '2014/09/5c8dd1a8c665562cd24249825645ec74.jpg'),
(116, 32, '_wp_attachment_metadata', 'a:5:{s:5:"width";i:440;s:6:"height";i:533;s:4:"file";s:44:"2014/09/5c8dd1a8c665562cd24249825645ec74.jpg";s:5:"sizes";a:5:{s:9:"thumbnail";a:4:{s:4:"file";s:44:"5c8dd1a8c665562cd24249825645ec74-150x150.jpg";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:10:"image/jpeg";}s:6:"medium";a:4:{s:4:"file";s:44:"5c8dd1a8c665562cd24249825645ec74-247x300.jpg";s:5:"width";i:247;s:6:"height";i:300;s:9:"mime-type";s:10:"image/jpeg";}s:9:"mag-image";a:4:{s:4:"file";s:44:"5c8dd1a8c665562cd24249825645ec74-340x160.jpg";s:5:"width";i:340;s:6:"height";i:160;s:9:"mime-type";s:10:"image/jpeg";}s:10:"blog-image";a:4:{s:4:"file";s:44:"5c8dd1a8c665562cd24249825645ec74-220x180.jpg";s:5:"width";i:220;s:6:"height";i:180;s:9:"mime-type";s:10:"image/jpeg";}s:17:"sb-post-thumbnail";a:4:{s:4:"file";s:42:"5c8dd1a8c665562cd24249825645ec74-70x70.jpg";s:5:"width";i:70;s:6:"height";i:70;s:9:"mime-type";s:10:"image/jpeg";}}s:10:"image_meta";a:11:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:0:"";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";s:11:"orientation";i:0;}}'),
(117, 2, '_thumbnail_id', '32'),
(118, 2, '_edit_last', '1'),
(119, 34, '_wp_attached_file', '2014/09/10409411_416363885159167_3634346411863629233_n.jpg'),
(120, 34, '_wp_attachment_metadata', 'a:5:{s:5:"width";i:261;s:6:"height";i:159;s:4:"file";s:58:"2014/09/10409411_416363885159167_3634346411863629233_n.jpg";s:5:"sizes";a:3:{s:9:"thumbnail";a:4:{s:4:"file";s:58:"10409411_416363885159167_3634346411863629233_n-150x150.jpg";s:5:"width";i:150;s:6:"height";i:150;s:9:"mime-type";s:10:"image/jpeg";}s:10:"blog-image";a:4:{s:4:"file";s:58:"10409411_416363885159167_3634346411863629233_n-220x159.jpg";s:5:"width";i:220;s:6:"height";i:159;s:9:"mime-type";s:10:"image/jpeg";}s:17:"sb-post-thumbnail";a:4:{s:4:"file";s:56:"10409411_416363885159167_3634346411863629233_n-70x70.jpg";s:5:"width";i:70;s:6:"height";i:70;s:9:"mime-type";s:10:"image/jpeg";}}s:10:"image_meta";a:11:{s:8:"aperture";i:0;s:6:"credit";s:0:"";s:6:"camera";s:0:"";s:7:"caption";s:0:"";s:17:"created_timestamp";i:0;s:9:"copyright";s:0:"";s:12:"focal_length";i:0;s:3:"iso";i:0;s:13:"shutter_speed";i:0;s:5:"title";s:0:"";s:11:"orientation";i:0;}}'),
(121, 10, '_thumbnail_id', '34');

-- --------------------------------------------------------

--
-- Table structure for table `wp_posts`
--

DROP TABLE IF EXISTS `wp_posts`;
CREATE TABLE IF NOT EXISTS `wp_posts` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `post_author` bigint(20) unsigned NOT NULL DEFAULT '0',
  `post_date` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_date_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content` longtext NOT NULL,
  `post_title` text NOT NULL,
  `post_excerpt` text NOT NULL,
  `post_status` varchar(20) NOT NULL DEFAULT 'publish',
  `comment_status` varchar(20) NOT NULL DEFAULT 'open',
  `ping_status` varchar(20) NOT NULL DEFAULT 'open',
  `post_password` varchar(20) NOT NULL DEFAULT '',
  `post_name` varchar(200) NOT NULL DEFAULT '',
  `to_ping` text NOT NULL,
  `pinged` text NOT NULL,
  `post_modified` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_modified_gmt` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `post_content_filtered` longtext NOT NULL,
  `post_parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `guid` varchar(255) NOT NULL DEFAULT '',
  `menu_order` int(11) NOT NULL DEFAULT '0',
  `post_type` varchar(20) NOT NULL DEFAULT 'post',
  `post_mime_type` varchar(100) NOT NULL DEFAULT '',
  `comment_count` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`ID`),
  KEY `post_name` (`post_name`),
  KEY `type_status_date` (`post_type`,`post_status`,`post_date`,`ID`),
  KEY `post_parent` (`post_parent`),
  KEY `post_author` (`post_author`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=35 ;

--
-- Dumping data for table `wp_posts`
--

INSERT INTO `wp_posts` (`ID`, `post_author`, `post_date`, `post_date_gmt`, `post_content`, `post_title`, `post_excerpt`, `post_status`, `comment_status`, `ping_status`, `post_password`, `post_name`, `to_ping`, `pinged`, `post_modified`, `post_modified_gmt`, `post_content_filtered`, `post_parent`, `guid`, `menu_order`, `post_type`, `post_mime_type`, `comment_count`) VALUES
(1, 1, '2014-09-29 16:51:28', '2014-09-29 16:51:28', 'Welcome to WordPress. This is your first post. Edit or delete it, then start blogging!', 'Hello world!', '', 'publish', 'open', 'open', '', 'hello-world', '', '', '2014-09-29 16:51:28', '2014-09-29 16:51:28', '', 0, 'http://localhost/wordpress/?p=1', 0, 'post', '', 1),
(2, 1, '2014-09-29 16:51:28', '2014-09-29 16:51:28', 'This is an example page. It''s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\r\n<blockquote>Hi there! I''m a bike messenger by day, aspiring actor by night, and this is my blog. I live in Los Angeles, have a great dog named Jack, and I like piña coladas. (And gettin'' caught in the rain.)</blockquote>\r\n...or something like this:\r\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\r\nAs a new WordPress user, you should go to <a href="http://localhost/wordpress/wp-admin/">your dashboard</a> to delete this page and create new pages for your content. Have fun!', 'Sample Page', '', 'publish', 'open', 'open', '', 'sample-page', '', '', '2014-09-30 17:24:21', '2014-09-30 17:24:21', '', 0, 'http://localhost/wordpress/?page_id=2', 0, 'page', '', 0),
(3, 1, '2014-09-29 16:51:52', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2014-09-29 16:51:52', '0000-00-00 00:00:00', '', 0, 'http://localhost/wordpress/?p=3', 0, 'post', '', 0),
(4, 1, '2014-09-29 16:54:03', '0000-00-00 00:00:00', '', 'Custom Favicon', '', 'draft', 'closed', 'closed', '', 'of-custom_favicon', '', '', '2014-09-29 16:54:03', '0000-00-00 00:00:00', '', 0, 'http://localhost/wordpress/?post_type=options&p=4', 0, 'options', '', 0),
(5, 1, '2014-09-29 16:54:03', '0000-00-00 00:00:00', '', 'Custom Logo', '', 'draft', 'closed', 'closed', '', 'of-custom_logo', '', '', '2014-09-29 16:54:03', '0000-00-00 00:00:00', '', 0, 'http://localhost/wordpress/?post_type=options&p=5', 0, 'options', '', 0),
(6, 1, '2014-09-29 17:00:08', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2014-09-29 17:00:08', '0000-00-00 00:00:00', '', 0, 'http://localhost/wordpress/?p=6', 0, 'post', '', 0),
(7, 1, '2014-09-29 17:30:14', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2014-09-29 17:30:14', '0000-00-00 00:00:00', '', 0, 'http://localhost/wordpress/?p=7', 0, 'post', '', 0),
(8, 1, '2014-09-29 17:44:20', '2014-09-29 17:44:20', '', 'logo31', '', 'inherit', 'open', 'open', '', 'logo31', '', '', '2014-09-29 17:44:20', '2014-09-29 17:44:20', '', 5, 'http://localhost/wordpress/wp-content/uploads/2014/09/logo31.png', 0, 'attachment', 'image/png', 0),
(9, 1, '2014-09-29 17:45:29', '2014-09-29 17:45:29', '', 'logo31', '', 'inherit', 'open', 'open', '', 'logo31-2', '', '', '2014-09-29 17:45:29', '2014-09-29 17:45:29', '', 5, 'http://localhost/wordpress/wp-content/uploads/2014/09/logo311.png', 0, 'attachment', 'image/png', 0),
(10, 1, '2014-09-30 11:19:52', '2014-09-30 11:19:52', 'Liên hệ với chúng tôi', 'Liên Hệ', '', 'publish', 'open', 'open', '', 'lien-he', '', '', '2014-09-30 11:22:16', '2014-09-30 11:22:16', '', 0, 'http://localhost/wordpress/?page_id=10', 0, 'page', '', 0),
(11, 1, '2014-09-30 11:19:52', '2014-09-30 11:19:52', 'Liên hệ với chúng tôi', 'Liên Hệ', '', 'inherit', 'open', 'open', '', '10-revision-v1', '', '', '2014-09-30 11:19:52', '2014-09-30 11:19:52', '', 10, 'http://localhost/wordpress/?p=11', 0, 'revision', '', 0),
(18, 1, '2014-09-30 11:38:18', '2014-09-30 11:38:18', 'Welcome to WordPress. This is your first post. Edit or delete it, then start blogging![huge_it_slider id="1"]', 'Hello world!', '', 'inherit', 'open', 'open', '', '1-autosave-v1', '', '', '2014-09-30 11:38:18', '2014-09-30 11:38:18', '', 1, 'http://localhost/wordpress/index.php/1-autosave-v1/', 0, 'revision', '', 0),
(20, 1, '2014-09-30 16:54:29', '2014-09-30 16:54:29', '<div><strong><a href="http://dichvudidong.vn/dang-ky-dich-vu-mfilm-xem-phim-truc-tuyen-cua-mobifone">Dịch vụ Mfilm Mobifone</a> - </strong>dịch vụ xem phim trực tuyến của MobiFone là dịch vụ cung cấp phim qua các thiết bị di động (điện thoại, máy tính bảng). Bạn có thể xem các bộ phim trong nước và quốc tế hấp dẫn nhất thật dễ dàng ngay trên điện thoại di động mọi lúc mọi nơi với chi phí cực kỳ hấp dẫn.</div>\r\n<div class="detail_img"><a href="http://dichvudidong.vn/wp-content/uploads/2014/08/logo.jpg"><img class="size-full wp-image-154 aligncenter img-responsive" src="http://dichvudidong.vn/wp-content/uploads/2014/08/logo.jpg" alt="logo" width="322" height="214" /></a></div>\r\n<div class="detail_img"></div>\r\n<div class="detail_img">Đối tượng sử dụng <strong>dịch vụ mfilm Mobifone</strong> là các thuê bao di động Mobifone đang hoạt động 2 chiều và điện thoại, máy tính bảng có hỗ trợ truy cập Internet và có tính năng streaming/tải <a href="http://dichvudidong.vn/dang-ky-dich-vu-video-giai-tri-mobiclip-mobifone" target="_blank">video</a></div>\r\n<div class="detail_img"></div>\r\n<div class="detail_img"><strong>Đăng ký sử dung:</strong></div>\r\n<div>\r\n<table class="table table-condensed table-striped table-bordered">\r\n<tbody>\r\n<tr>\r\n<th><b>Tên dịch vụ</b></th>\r\n<th><b>Mã</b></th>\r\n<th><b>Giá cước\r\n(VNĐ)</b></th>\r\n<th><b>Chu kỳ\r\n(ngày)</b></th>\r\n<th>SMS đăng ký</th>\r\n</tr>\r\n<tr>\r\n<td><strong>MFILM</strong></td>\r\n<td>MF</td>\r\n<td>19.000</td>\r\n<td>30</td>\r\n<td>ON MF gởi <strong>9084</strong></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</div>\r\n<div>\r\n\r\n<strong>Cài đặt nhanh dịch vụ MFilm của Mobifone bằng cú pháp:</strong>\r\n\r\nXem phim trực tuyến: Soạn <strong>ON <span class="sms_struct">MF</span></strong> gởi <strong>9084</strong>\r\n\r\n<span data-mce-mark="1">+ Khách hàng được miễn phí download 3 phim đầu tiên, từ phim thứ 4 trở đi phí download là từ 0-5.000 VNĐ</span>\r\n\r\n+ Cước gửi tin nhắn đến đầu số 9084: Miễn phí\r\n\r\n+ Cước Data khi sử dung dịch vụ : Miễn Phí\r\n\r\n<strong>Sử dung dịch vụ</strong>:\r\n\r\n- <strong>Qua Wapsite</strong>: Truy cập wapsite: http://mfilm.vn  qua <a href="http://dichvudidong.vn/dang-ky-dich-vu-3g-mobile-internet-cho-mobifone" target="_blank">3G Mobifone</a> hoặc wifi  -&gt; lựa chon nội dung và bấm nút xem/Tải/Tặng trên từng nội dung.\r\n\r\n- <strong>Qua Ứng dụng</strong>:  Để tải và cài đặt ứng dụng <strong>MFilm</strong> khách hàng có thể truy cập trang web http://mfilm.vn (đối với điện thoại, máy tính bảng sử dụng hệ điều hành Android), download trên Appstore với các điện thoại, máy tính bảng sử dụng hệ điều hành IOS. Cước tải Ứng dụng dịch vụ (Client): Miễn phí<strong>.</strong>\r\n\r\n<em>Ghi chú:</em>\r\n\r\n- Chi tiết mức cước của từng phim sẽ được niêm yết theo từng lượt mua (xem, tải, tặng) trước khi thực hiện giao dịch.\r\n\r\n- Cước đăng ký nhận lịch chiếu phim hàng tuần, ngày: Miễn phí.\r\n\r\nNgoài ra khi <a href="http://dichvudidong.vn/dang-ky-dich-vu-xem-phim-truc-tuyen-mfilm-mobifone">đăng kí dịch vụ Mfilm Mobifone</a> tại dichvudidong.vn<strong> </strong>các bạn còn được cập nhật thông tin các bộ phim hot trong tuần, tháng. Hãy liên hệ ngay bộ phận tư vấn online của <a href="http://dichvudidong.vn/" target="_blank">dichvudidong.vn</a> nhé!!!\r\n\r\n</div>', 'MF-MFILM', '', 'publish', 'open', 'open', '', 'dang-ky-dich-vu-xem-phim-truc-tuyen-mfilm-mobifone', '', '', '2014-09-30 17:23:45', '2014-09-30 17:23:45', '', 0, 'http://localhost/wordpress/?page_id=20', 0, 'page', '', 0),
(21, 1, '2014-09-30 16:52:04', '2014-09-30 16:52:04', '', '3854_RinTinTin', '', 'inherit', 'open', 'open', '', '3854_rintintin', '', '', '2014-09-30 16:52:04', '2014-09-30 16:52:04', '', 20, 'http://localhost/wordpress/wp-content/uploads/2014/09/3854_RinTinTin.jpg', 0, 'attachment', 'image/jpeg', 0),
(22, 1, '2014-09-30 16:54:29', '2014-09-30 16:54:29', '<div><strong><a href="http://dichvudidong.vn/dang-ky-dich-vu-mfilm-xem-phim-truc-tuyen-cua-mobifone">Dịch vụ Mfilm Mobifone</a> - </strong>dịch vụ xem phim trực tuyến của MobiFone là dịch vụ cung cấp phim qua các thiết bị di động (điện thoại, máy tính bảng). Bạn có thể xem các bộ phim trong nước và quốc tế hấp dẫn nhất thật dễ dàng ngay trên điện thoại di động mọi lúc mọi nơi với chi phí cực kỳ hấp dẫn.</div>\r\n<div class="detail_img"><a href="http://dichvudidong.vn/wp-content/uploads/2014/08/logo.jpg"><img class="size-full wp-image-154 aligncenter img-responsive" src="http://dichvudidong.vn/wp-content/uploads/2014/08/logo.jpg" alt="logo" width="322" height="214" /></a></div>\r\n<div class="detail_img"></div>\r\n<div class="detail_img">Đối tượng sử dụng <strong>dịch vụ mfilm Mobifone</strong> là các thuê bao di động Mobifone đang hoạt động 2 chiều và điện thoại, máy tính bảng có hỗ trợ truy cập Internet và có tính năng streaming/tải <a href="http://dichvudidong.vn/dang-ky-dich-vu-video-giai-tri-mobiclip-mobifone" target="_blank">video</a></div>\r\n<div class="detail_img"></div>\r\n<div class="detail_img"><strong>Đăng ký sử dung:</strong></div>\r\n<div>\r\n<table class="table table-condensed table-striped table-bordered">\r\n<tbody>\r\n<tr>\r\n<th><b>Tên dịch vụ</b></th>\r\n<th><b>Mã</b></th>\r\n<th><b>Giá cước\r\n(VNĐ)</b></th>\r\n<th><b>Chu kỳ\r\n(ngày)</b></th>\r\n<th>SMS đăng ký</th>\r\n</tr>\r\n<tr>\r\n<td><strong>MFILM</strong></td>\r\n<td>MF</td>\r\n<td>19.000</td>\r\n<td>30</td>\r\n<td>ON MF gởi <strong>9084</strong></td>\r\n</tr>\r\n</tbody>\r\n</table>\r\n</div>\r\n<div>\r\n\r\n<strong>Cài đặt nhanh dịch vụ MFilm của Mobifone bằng cú pháp:</strong>\r\n\r\nXem phim trực tuyến: Soạn <strong>ON <span class="sms_struct">MF</span></strong> gởi <strong>9084</strong>\r\n\r\n<span data-mce-mark="1">+ Khách hàng được miễn phí download 3 phim đầu tiên, từ phim thứ 4 trở đi phí download là từ 0-5.000 VNĐ</span>\r\n\r\n+ Cước gửi tin nhắn đến đầu số 9084: Miễn phí\r\n\r\n+ Cước Data khi sử dung dịch vụ : Miễn Phí\r\n\r\n<strong>Sử dung dịch vụ</strong>:\r\n\r\n- <strong>Qua Wapsite</strong>: Truy cập wapsite: http://mfilm.vn  qua <a href="http://dichvudidong.vn/dang-ky-dich-vu-3g-mobile-internet-cho-mobifone" target="_blank">3G Mobifone</a> hoặc wifi  -&gt; lựa chon nội dung và bấm nút xem/Tải/Tặng trên từng nội dung.\r\n\r\n- <strong>Qua Ứng dụng</strong>:  Để tải và cài đặt ứng dụng <strong>MFilm</strong> khách hàng có thể truy cập trang web http://mfilm.vn (đối với điện thoại, máy tính bảng sử dụng hệ điều hành Android), download trên Appstore với các điện thoại, máy tính bảng sử dụng hệ điều hành IOS. Cước tải Ứng dụng dịch vụ (Client): Miễn phí<strong>.</strong>\r\n\r\n<em>Ghi chú:</em>\r\n\r\n- Chi tiết mức cước của từng phim sẽ được niêm yết theo từng lượt mua (xem, tải, tặng) trước khi thực hiện giao dịch.\r\n\r\n- Cước đăng ký nhận lịch chiếu phim hàng tuần, ngày: Miễn phí.\r\n\r\nNgoài ra khi <a href="http://dichvudidong.vn/dang-ky-dich-vu-xem-phim-truc-tuyen-mfilm-mobifone">đăng kí dịch vụ Mfilm Mobifone</a> tại dichvudidong.vn<strong> </strong>các bạn còn được cập nhật thông tin các bộ phim hot trong tuần, tháng. Hãy liên hệ ngay bộ phận tư vấn online của <a href="http://dichvudidong.vn/" target="_blank">dichvudidong.vn</a> nhé!!!\r\n\r\n</div>', 'MF-MFILM', '', 'inherit', 'open', 'open', '', '20-revision-v1', '', '', '2014-09-30 16:54:29', '2014-09-30 16:54:29', '', 20, 'http://localhost/wordpress/index.php/20-revision-v1/', 0, 'revision', '', 0),
(26, 1, '2014-09-30 17:01:57', '2014-09-30 17:01:57', '', 'Home', '', 'publish', 'open', 'open', '', 'home', '', '', '2014-09-30 17:04:48', '2014-09-30 17:04:48', '', 0, 'http://localhost/wordpress/?p=26', 1, 'nav_menu_item', '', 0),
(27, 1, '2014-09-30 17:01:57', '2014-09-30 17:01:57', ' ', '', '', 'publish', 'open', 'open', '', '27', '', '', '2014-09-30 17:04:48', '2014-09-30 17:04:48', '', 0, 'http://localhost/wordpress/?p=27', 2, 'nav_menu_item', '', 0),
(28, 1, '2014-09-30 17:01:57', '2014-09-30 17:01:57', ' ', '', '', 'publish', 'open', 'open', '', '28', '', '', '2014-09-30 17:04:48', '2014-09-30 17:04:48', '', 0, 'http://localhost/wordpress/?p=28', 3, 'nav_menu_item', '', 0),
(29, 1, '2014-09-30 17:02:32', '2014-09-30 17:02:32', ' ', '', '', 'publish', 'open', 'open', '', '29', '', '', '2014-09-30 17:04:48', '2014-09-30 17:04:48', '', 4, 'http://localhost/wordpress/?p=29', 4, 'nav_menu_item', '', 0),
(30, 1, '2014-09-30 17:04:48', '2014-09-30 17:04:48', ' ', '', '', 'publish', 'open', 'open', '', '30', '', '', '2014-09-30 17:04:48', '2014-09-30 17:04:48', '', 0, 'http://localhost/wordpress/?p=30', 5, 'nav_menu_item', '', 0),
(31, 1, '2014-09-30 17:23:50', '0000-00-00 00:00:00', '', 'Auto Draft', '', 'auto-draft', 'open', 'open', '', '', '', '', '2014-09-30 17:23:50', '0000-00-00 00:00:00', '', 0, 'http://localhost/wordpress/?page_id=31', 0, 'page', '', 0),
(32, 1, '2014-09-30 17:24:16', '2014-09-30 17:24:16', '', '5c8dd1a8c665562cd24249825645ec74', '', 'inherit', 'open', 'open', '', '5c8dd1a8c665562cd24249825645ec74', '', '', '2014-09-30 17:24:16', '2014-09-30 17:24:16', '', 2, 'http://localhost/wordpress/wp-content/uploads/2014/09/5c8dd1a8c665562cd24249825645ec74.jpg', 0, 'attachment', 'image/jpeg', 0),
(33, 1, '2014-09-30 17:24:21', '2014-09-30 17:24:21', 'This is an example page. It''s different from a blog post because it will stay in one place and will show up in your site navigation (in most themes). Most people start with an About page that introduces them to potential site visitors. It might say something like this:\r\n<blockquote>Hi there! I''m a bike messenger by day, aspiring actor by night, and this is my blog. I live in Los Angeles, have a great dog named Jack, and I like piña coladas. (And gettin'' caught in the rain.)</blockquote>\r\n...or something like this:\r\n<blockquote>The XYZ Doohickey Company was founded in 1971, and has been providing quality doohickeys to the public ever since. Located in Gotham City, XYZ employs over 2,000 people and does all kinds of awesome things for the Gotham community.</blockquote>\r\nAs a new WordPress user, you should go to <a href="http://localhost/wordpress/wp-admin/">your dashboard</a> to delete this page and create new pages for your content. Have fun!', 'Sample Page', '', 'inherit', 'open', 'open', '', '2-revision-v1', '', '', '2014-09-30 17:24:21', '2014-09-30 17:24:21', '', 2, 'http://localhost/wordpress/index.php/2-revision-v1/', 0, 'revision', '', 0),
(34, 1, '2014-09-30 18:24:31', '2014-09-30 18:24:31', '', '10409411_416363885159167_3634346411863629233_n', '', 'inherit', 'open', 'open', '', '10409411_416363885159167_3634346411863629233_n', '', '', '2014-09-30 18:24:31', '2014-09-30 18:24:31', '', 10, 'http://localhost/wordpress/wp-content/uploads/2014/09/10409411_416363885159167_3634346411863629233_n.jpg', 0, 'attachment', 'image/jpeg', 0);

-- --------------------------------------------------------

--
-- Table structure for table `wp_terms`
--

DROP TABLE IF EXISTS `wp_terms`;
CREATE TABLE IF NOT EXISTS `wp_terms` (
  `term_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(200) NOT NULL DEFAULT '',
  `slug` varchar(200) NOT NULL DEFAULT '',
  `term_group` bigint(10) NOT NULL DEFAULT '0',
  PRIMARY KEY (`term_id`),
  UNIQUE KEY `slug` (`slug`),
  KEY `name` (`name`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=9 ;

--
-- Dumping data for table `wp_terms`
--

INSERT INTO `wp_terms` (`term_id`, `name`, `slug`, `term_group`) VALUES
(1, 'Uncategorized', 'uncategorized', 0),
(3, 'Tin Tức', 'tin-tuc', 0),
(4, 'Đăng Ký Dịch Vụ', 'dang-ky-dich-vu', 0),
(5, 'Mobile Internet 3G', 'mobile-internet-3g', 0),
(8, 'Home', 'home', 0);

-- --------------------------------------------------------

--
-- Table structure for table `wp_term_relationships`
--

DROP TABLE IF EXISTS `wp_term_relationships`;
CREATE TABLE IF NOT EXISTS `wp_term_relationships` (
  `object_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `term_taxonomy_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `term_order` int(11) NOT NULL DEFAULT '0',
  PRIMARY KEY (`object_id`,`term_taxonomy_id`),
  KEY `term_taxonomy_id` (`term_taxonomy_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `wp_term_relationships`
--

INSERT INTO `wp_term_relationships` (`object_id`, `term_taxonomy_id`, `term_order`) VALUES
(1, 1, 0),
(26, 11, 0),
(27, 11, 0),
(28, 11, 0),
(29, 11, 0),
(30, 11, 0);

-- --------------------------------------------------------

--
-- Table structure for table `wp_term_taxonomy`
--

DROP TABLE IF EXISTS `wp_term_taxonomy`;
CREATE TABLE IF NOT EXISTS `wp_term_taxonomy` (
  `term_taxonomy_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `term_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `taxonomy` varchar(32) NOT NULL DEFAULT '',
  `description` longtext NOT NULL,
  `parent` bigint(20) unsigned NOT NULL DEFAULT '0',
  `count` bigint(20) NOT NULL DEFAULT '0',
  PRIMARY KEY (`term_taxonomy_id`),
  UNIQUE KEY `term_id_taxonomy` (`term_id`,`taxonomy`),
  KEY `taxonomy` (`taxonomy`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=12 ;

--
-- Dumping data for table `wp_term_taxonomy`
--

INSERT INTO `wp_term_taxonomy` (`term_taxonomy_id`, `term_id`, `taxonomy`, `description`, `parent`, `count`) VALUES
(1, 1, 'category', '', 0, 1),
(3, 3, 'category', '', 0, 0),
(4, 4, 'category', '', 0, 0),
(5, 5, 'category', '', 4, 0),
(11, 8, 'nav_menu', '', 0, 5);

-- --------------------------------------------------------

--
-- Table structure for table `wp_usermeta`
--

DROP TABLE IF EXISTS `wp_usermeta`;
CREATE TABLE IF NOT EXISTS `wp_usermeta` (
  `umeta_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_id` bigint(20) unsigned NOT NULL DEFAULT '0',
  `meta_key` varchar(255) DEFAULT NULL,
  `meta_value` longtext,
  PRIMARY KEY (`umeta_id`),
  KEY `user_id` (`user_id`),
  KEY `meta_key` (`meta_key`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=21 ;

--
-- Dumping data for table `wp_usermeta`
--

INSERT INTO `wp_usermeta` (`umeta_id`, `user_id`, `meta_key`, `meta_value`) VALUES
(1, 1, 'nickname', 'admin'),
(2, 1, 'first_name', ''),
(3, 1, 'last_name', ''),
(4, 1, 'description', ''),
(5, 1, 'rich_editing', 'true'),
(6, 1, 'comment_shortcuts', 'false'),
(7, 1, 'admin_color', 'fresh'),
(8, 1, 'use_ssl', '0'),
(9, 1, 'show_admin_bar_front', 'true'),
(10, 1, 'wp_capabilities', 'a:1:{s:13:"administrator";b:1;}'),
(11, 1, 'wp_user_level', '10'),
(12, 1, 'dismissed_wp_pointers', 'wp350_media,wp360_revisions,wp360_locks,wp390_widgets'),
(13, 1, 'show_welcome_panel', '1'),
(14, 1, 'session_tokens', 'a:3:{s:64:"cda38e6d306617683d8785729e99957070deed6de4d506c096d177f6a9c09511";i:1412182306;s:64:"bd71be2ce182c923d49286c40f9e0d918414ad00d4a4b5fef7cf635c4d4bd252";i:1412248714;s:64:"111101df7a23dcfd73450ecfce279bd127a7f9de523d7643c527c7e503eaa183";i:1412268382;}'),
(15, 1, 'wp_dashboard_quick_press_last_post_id', '3'),
(16, 1, 'managenav-menuscolumnshidden', 'a:4:{i:0;s:11:"link-target";i:1;s:11:"css-classes";i:2;s:3:"xfn";i:3;s:11:"description";}'),
(17, 1, 'metaboxhidden_nav-menus', 'a:2:{i:0;s:8:"add-post";i:1;s:12:"add-post_tag";}'),
(18, 1, 'nav_menu_recently_edited', '8'),
(19, 1, 'wp_user-settings', 'posts_list_mode=list&libraryContent=browse'),
(20, 1, 'wp_user-settings-time', '1412095578');

-- --------------------------------------------------------

--
-- Table structure for table `wp_users`
--

DROP TABLE IF EXISTS `wp_users`;
CREATE TABLE IF NOT EXISTS `wp_users` (
  `ID` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `user_login` varchar(60) NOT NULL DEFAULT '',
  `user_pass` varchar(64) NOT NULL DEFAULT '',
  `user_nicename` varchar(50) NOT NULL DEFAULT '',
  `user_email` varchar(100) NOT NULL DEFAULT '',
  `user_url` varchar(100) NOT NULL DEFAULT '',
  `user_registered` datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
  `user_activation_key` varchar(60) NOT NULL DEFAULT '',
  `user_status` int(11) NOT NULL DEFAULT '0',
  `display_name` varchar(250) NOT NULL DEFAULT '',
  PRIMARY KEY (`ID`),
  KEY `user_login_key` (`user_login`),
  KEY `user_nicename` (`user_nicename`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=2 ;

--
-- Dumping data for table `wp_users`
--

INSERT INTO `wp_users` (`ID`, `user_login`, `user_pass`, `user_nicename`, `user_email`, `user_url`, `user_registered`, `user_activation_key`, `user_status`, `display_name`) VALUES
(1, 'admin', '$P$BFXeQ7tEJg6FPlh2XPmwX3/UlTDHJS0', 'admin', 'daobv@gmail.com', '', '2014-09-29 16:51:26', '', 0, 'admin');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
